<?php
/**
 * Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'RELEASE_NOTES_DASHBOARD_JS', 'dashboard-31d6cfe0.js' );
define( 'RELEASE_NOTES_EDITOR_JS', 'editor-071c76ff.js' );
define( 'RELEASE_NOTES_DASHBOARD_CSS', 'dashboard-2d07d2f6.css' );

define( 'RELEASE_NOTES_VERSION', '1.0.0-alpha.1' );
